app = "mautrix-meta-instagram"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  UID = "1337"
  GID = "1337"

[mounts]
  source = "mautrix_meta_data"
  destination = "/data"

[[services]]
  internal_port = 29319
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
