# fly.toml app configuration file generated for mautrix-meta-instagram on 2025-10-04T14:17:11+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mautrix-meta-instagram'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  GID = '1337'
  UID = '1337'

[http_service]
  internal_port = 29319
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
